### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by imrany** [BurajeVallary/Portfolio#1]
Hey Valary

**Comment by BurajeVallary** [comment]
Hey Imran

**Comment by imrany** [comment]
I saw your follow :).... how are doing?

**Comment by BurajeVallary** [comment]
I'm doing great!
Just keeping up with studies

**Comment by imrany** [comment]
Ooh that's great.

**Comment by BurajeVallary** [comment]
How are you from your side?

**Comment by imrany** [comment]
I'm also fine... just coding

**Comment by BurajeVallary** [comment]
What are you currently working on?

**Comment by imrany** [comment]
I've been working on multiple project but in the health niche

**Comment by BurajeVallary** [comment]
😂I was just looking at your Github  and comparing them with mine, I'm like
weee🤦‍♀️

**Comment by imrany** [comment]
My repo aren't that complex or hard to understand. it comes with time... I'm also learning

**Comment by BurajeVallary** [comment]
Yeaaah,bet with time I'll understand them better

**Comment by imrany** [comment]
I'm stilll learning by the way.... When i'm done with my recent project,  i'll send you

**Comment by BurajeVallary** [comment]
It seems like  you are already a pro innit
For me there was a hackathon project we were doing for creating websites
and adding js into it
For my group we were working on a movie streaming website
*Vallary Buraje*

**Comment by imrany** [comment]
what's the prize

**Comment by BurajeVallary** [comment]
It was a school project,was't that serious as persay
But we were no2

**Comment by imrany** [comment]
okay [my whatsapp](https://wa.me/254732720752) ....we can chat more

**Comment by imrany** [comment]
if you'll have any ideas.. we can collaborate on a future project or start-up and also create a group and profit out of it.

**Comment by BurajeVallary** [comment]
The phone number aint in whatapp

**Comment by imrany** [comment]
[ooh sorry, i made a typo [my whatsapp](https://wa.me/254734720752)

**Comment by BurajeVallary** [comment]
Its okay,I have texted you

**Comment by imrany** [comment]
Seen it.... saved

**Comment by BurajeVallary** [comment]
Okay thank you

**Comment by BurajeVallary** [comment]
https://ubiquitous-souffle-e61062.netlify.app/


*Vallary Buraje*
